apiVersion: apps/v1
kind: Deployment
metadata:
  name: d3compare-deployment
  labels:
    app: d3compare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: d3compare
  template:
    metadata:
      labels:
        app: d3compare
    spec:
      containers:
        - name: d3compare
          image: egdetti/d3compare:1.14.0
          env:
            - name: D3_CLIENT_ID
              value: ${D3_CLIENT_ID}
            - name: D3_CLIENT_SECRET
              value: ${D3_CLIENT_SECRET}
            - name: D3COMPARE_URL
              value: ${D3COMPARE_URL}
          ports:
            - containerPort: 8080
