d3:
  clientId: ${D3_CLIENT_ID}
  clientSecret: ${D3_CLIENT_SECRET}

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            clientId: ${D3_CLIENT_ID}
            clientSecret: ${D3_CLIENT_SECRET}
        provider:
          keycloak:
            issuer-uri: https://us.battle.net/oauth
